### ISSUE TITLE
Unable to use gitea-action-release for file uploads on Gitea

### ISSUE THREAD

**Issue by triggered96** [sigyl-actions/gitea-action-release#1]
### Issue Description:

I encountered an issue while attempting to upload files using gitea-action-release. I tried using [svenstaro/upload-release-action](https://github.com/svenstaro/upload-release-action) for uploading, but found that the action supports only GitHub and not Gitea.

### Steps to Reproduce:

In my Gitea repository, use the following workflow file:
```
name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/my*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
```

### Expected Behavior:

Files should be successfully uploaded to the Gitea release.

### Actual Behavior:

Due to [svenstaro/upload-release-action](https://github.com/svenstaro/upload-release-action) not supporting Gitea, the files cannot be successfully uploaded.

### Additional Information:

1. [ ] [ ] Gitea Version:
2. [ ] [ ] Gitea-action-release Version:
3. [ ] [ ] Does the above issue impact your workflow? Yes/No

### Suggested Solution:

Consider using other upload actions that support Gitea or explore alternative solutions to successfully upload files on Gitea.
